# Generated by Django 3.0.8 on 2020-07-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_snippet_original_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(max_length=500),
        ),
    ]
