# Generated by Django 3.0.8 on 2020-07-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20200708_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='date_added',
            field=models.DateField(auto_now_add=True, default='1969-12-31'),
            preserve_default=False,
        ),
    ]
